[package]
name = "core1_etb"
version = "0.1.0"
edition = "2021"

[dependencies]
umya-spreadsheet = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
calamine = "0.24"
zip = "2.4.2"

anyhow = "1.0"
dotenvy = "0.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

reqwest = { version = "0.12", features = ["blocking", "json"] }

aws-config = "1"
aws-sdk-translate = "1"
